### PR TITLE
Add RustResources plugin and Cooldowns by IAmSilK

### PR DESCRIPTION
**Pull request by negrifelipe**

### CODE REVIEW

**Comment by Trojaner** [comment]
Cooldowns will not be added as it will be an official plugin

**Comment by negrifelipe** [comment]
> Cooldowns will not be added as it will be an official plugin

and my plugin?

**Comment by Trojaner** [comment]
Your plugin is missing a license file inside the repository.

**Comment by negrifelipe** [comment]
oh sorry, i have added the license😀

**Comment by Trojaner** [comment]
Please remove the cooldowns plugin so I can merge

**Comment by negrifelipe** [comment]
i have removed the cooldown plugin 😄 Now i can go to my bed and sleep 😴

**Pull request merged**
